Description: >
  Cloudfront distribution for UdaPeople.
Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String


Resources:
  
  UdapeopleCloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  UdapeopleWebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub
              - "frontend-udacity-udapeople-${WorkflowID}.s3.amazonaws.com"
              - { ID: !Select [0, !Split [ "-", !Ref WorkflowID] ] }
            Id: webpage
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${UdapeopleCloudFrontOriginAccessIdentity}"
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowwID}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowwID