---
  - name: "show remote environment"
    shell: env

  - name: "copy backend dependency"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/udapeople
      recursive: true

  - name: "copy node_modules to destination"
    become: yes
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/udapeople
      recursive: true

  - name: "start server"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: ~/udapeople/