version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  onfail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: ech "Job fail"
      - run: 
          command: echo "Pre Step Fails "
          when: on_fail
    
workflows:
  welcome:
    jobs:
      - onfail