version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  share_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Share output file"
          command: |
            echo "Hello World ! " > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_file_output:
    docker:
        - image: circleci/node:13.8.0
    steps:
        - checkout
        - attach_workspace:
            at: ~/
        - run:
            name: "Print output file"
            command: |
              cat ~/output.txt
            
workflows:
  welcome:
    jobs:
      - share_file
      - print_file_output:
          requires:
            - share_file