version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

commands:
  print_pipeline_id:
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  reuse_cmd:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
    
workflows:
  welcome:
    jobs:
      - reuse_cmd