version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_env:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say Environment variable name"
          command: echo $Name

workflows:
  welcome:
    jobs:
      - print_env