version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs: 
  build_backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: npm install and build
          working_directory: ./backend
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - backend/node_modules
            - backend/dist

  build_frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: npm install and build
          working_directory: ./frontend
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - frontend/node_modules

  backend_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
         name: npm test 
         working_directory: ./backend
         command: |
           npm run test

  frontend_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
         name: npm test 
         working_directory: ./frontend
         command: |
           npm run test

  backend_scan:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
         name: Scan Vulnerabilities Backend 
         working_directory: ./backend
         command: |
           npm audit fix --audit-level critical
        
workflows:
  welcome:
    jobs:
      - build_backend
      - build_frontend
      - backend_test:
          requires:
            - build_backend
      - frontend_test:
          requires:
            - build_frontend
      - backend_scan:
          requires:
            - build_backend 